version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:dev
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5001:5000
      - 3000:3000
      - 9228:9228
      - 9229:9229
